services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10

  backend-go:
    build: go
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9001:9000"
    environment:
      DB_HOST: db

  backend-python:
    build: python
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9002:9000"
    environment:
      DB_HOST: db